Repository Buscedv/Ask, pull requests merged in 2020-12, with the labels that each got.

#39 New DB datatype: bytes. New DB action: desc
  ask.py
Labels: enhancement

#43 changed string concatenations to f-strings, fixed two typos
  CONTRIBUTING.md
  README.md
  ask.py
Labels: enhancement

#44 turn 033 syntax into a styling string method
  ask-watch.py
  ask.py
Labels: code quality

#48 Added support for storing lists in the database.
  ask.py
Labels: new feature

#54 Built-in & custom Decorators
  ask.py
  test_ask.py
Labels: new feature

#55 Automatically generate the _init() and s() methods for database models, triggered by a decorator
  ask.py
Labels: new feature
